name: davekeyes
favicon: null
layout_spectrum: 0.2266946325544268
typography_spectrum: 0.25993227981962264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5487172387074679
  lightness: 0.5782038560137153
  saturation: 0.625240993918851
  rhythmicContrast: 0.9685707679018378
purpose: []
