name: davekeyes
favicon: null
layout_spectrum: 0.51769
typography_spectrum: 1
title: Pattern Library
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafbfc'
    - '#021b3e'
    - '#b7b8b9'
    - '#858686'
    - '#007dc3'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
